## 開發環境配置

[database]
# 使用開發環境數據庫
host = "db"  # 在Docker環境中使用服務名稱而非localhost
port = 5432
username = "backtest_server"
password = "backtest_server"
database = "backtest_server"
connection_pool_size = 10
max_connections = 10
min_connections = 2
max_lifetime_secs = 1800  # 秒, 30分鐘
acquire_timeout_secs = 15  # 秒，增加超時時間
idle_timeout_secs = 600   # 秒, 10分鐘

[log]
# 開發環境使用更詳細的日誌
level = "debug"
format = "pretty" 

[app]
# 開發環境使用不同端口
threads = 4

[strategy]
# 策略配置
directory = "strategies"               # 策略目錄路徑
hot_update_enabled = true              # 是否啟用熱更新
hot_update_interval_secs = 30          # 熱更新檢查間隔（秒）
config_watch_interval_secs = 15        # 配置文件監控間隔（秒）
max_parallel_updates = 5               # 最大並行更新數量
auto_reload_on_config_change = true    # 配置更新自動重載

[server]
# 伺服器配置
host = "127.0.0.1"
port = 3000  # 使用與原來 app.port 相同的端口
worker_threads = 4
request_timeout = 30  # 秒
max_connections = 1000
use_https = false
cert_path = ""  # 空字符串
key_path = ""   # 空字符串
enable_compression = true
max_body_size = 10485760  # 10MB
enable_cors = true  # 伺服器本身的CORS設定
cors_allowed_origins = ["http://localhost:8080"]  # 允許從前端頁面訪問
static_files_dir = "static"  # 靜態文件目錄

# 添加Redis配置部分，提供給開發環境使用

[redis]
url = "redis://localhost:6379"
pool_size = 10
connection_timeout_secs = 10
read_timeout_secs = 5
write_timeout_secs = 5
reconnect_attempts = 3
reconnect_delay_secs = 1

[rabbitmq]
url = "amqp://guest:guest@localhost:5672/"
pool_size = 10
connection_timeout_secs = 5
retry_interval_secs = 1
max_retries = 5
default_exchange_type = "direct"
default_exchange = "backtest.direct"
durable_messages = true
publish_confirm = true
prefetch_count = 10
consumer_tag_prefix = "backtest_server"