## 生產環境配置

[market_database]
# 市場數據資料庫（唯讀）
host = "marketdb.production"
port = 5432
username = "market_reader"
password = "market_reader_prod"
database = "marketdata_prod"
connection_pool_size = 30
max_connections = 60
min_connections = 15
# 優化連接生命週期
max_lifetime_secs = 1800  # 秒, 30分鐘
acquire_timeout_secs = 5  # 秒
idle_timeout_secs = 600   # 秒, 10分鐘

[backtest_database]
# 回測資料庫（讀寫）
host = "backtestdb.production"
port = 5432
username = "backtest_server"
password = "production_password"
database = "backtest_server_prod"
connection_pool_size = 20
max_connections = 50
min_connections = 10
# 優化連接生命週期
max_lifetime_secs = 1800  # 秒, 30分鐘
acquire_timeout_secs = 5  # 秒
idle_timeout_secs = 600   # 秒, 10分鐘

[log]
# 生產環境使用更簡潔的日誌
level = "info"
format = "json"

[app]
# 生產環境使用標準端口
threads = 16

[strategy]
# 策略配置
directory = "strategies"   # 策略目錄路徑
hot_update_enabled = true                  # 是否啟用熱更新
hot_update_interval_secs = 60              # 熱更新檢查間隔（秒）
config_watch_interval_secs = 30            # 配置文件監控間隔（秒）
max_parallel_updates = 5                   # 最大並行更新數量
auto_reload_on_config_change = true        # 配置更新自動重載 

[server]
# 伺服器配置
host = "0.0.0.0"  # 生產環境監聽所有網路接口
port = 80  # 使用與原來 app.port 相同的端口
worker_threads = 16
request_timeout = 30  # 秒
max_connections = 5000
use_https = true
cert_path = "/etc/backtest_server/ssl/cert.pem"
key_path = "/etc/backtest_server/ssl/key.pem"
enable_compression = true
max_body_size = 5242880  # 5MB
enable_cors = true
cors_allowed_origins = ["https://app.backtest_server.com", "https://api.backtest_server.com"]
static_files_dir = "/var/www/backtest_server/static"
